# Generated by Django 5.0.6 on 2024-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="schedule_publish",
        ),
        migrations.AddField(
            model_name="post",
            name="schedule_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
